### PR TITLE
travis: add some source/lint tests

### PR DESCRIPTION
**Pull request by vapier**
We probably should look into cpplint, but until then, these are
some simple hacks to catch common mistakes.

### CODE REVIEW

**Comment by cmb69** [comment]
Thanks. LGTM!

Before going further, we should adopt some coding style guide.

**Comment by vapier** [comment]
strongly agree.  i'll see about sketching out a md file based on the style that seems to be active in the codebase.

i'm not familiar with any C/C++ linters other than [cpplint](https://github.com/google/styleguide/tree/gh-pages/cpplint).  not sure if we'll be able to configure that in a way that works for our codebase.

**Comment by cmb69** [comment]
I'm not familiar with any C/C++ linters at all, so feel free to introduce whatever you prefer. However, for me it's way more important to have a documented coding style than to be able to automatically check the sources for compliance.

**Comment by vapier** [comment]
i've come across [clang-tidy](http://clang.llvm.org/extra/clang-tidy/) that i think we'd be able to shape for our needs

**Pull request merged**
