### PR TITLE
Fix #589: install dependencies move to .travis.yml

### LINKED ISSUE #589: travis failed on OSX platform
I merged a PR `add testcase for gdImageCopyResized` to master branch with CI failed on OSX. And then I reset to the previous commit, because my PR need to be improve. But the CI still failed only OSX. 

I have checked the Job Log, it shows the following message while `brew install`:
```
Error: webp 1.0.3 is already installed
To upgrade to 1.1.0, run `brew upgrade webp`.
```
Obviously the failure is caused by the version of webp in brew repo has updated from `1.0.3` to `1.1.0`.

### PR DESCRIPTION
**Pull request by willson-chen**
Use native method to install dependencies install of brew install manually.

### CODE REVIEW

**Comment by willson-chen** [comment]
Reference to #589. Discussion about the reason appended in that issue, while Dicussion about the code appended here.

**Comment by willson-chen** [comment]
I use `update: true` in the end of `homebrew:` block, which equals to excute `brew update`. But finally I decide to delete it. There are two reasons:
1. `brew update` make the time CI process longer. It takes about 160 seconds, but useless I think.
2. `brew update` will cause a test failure because of the `python3` lost. We run a python script named `whitespace.py` and located under `tests/source`, although I am not sure about what it is used for.

**Comment by willson-chen** [comment]
This is an urgent PR, please help to review.

**Comment by cmb69** [comment]
This looks good to me, thanks!

whitespace.py is part of CI, and checks for some whitespace errors in code.

**Comment by willson-chen** [comment]
> This looks good to me, thanks!
> 
> whitespace.py is part of CI, and checks for some whitespace errors in code.

Thanks for your review. I will merge it.

**Pull request merged**
