### PR TITLE
cmake: unify package & library versioning info #164

### PR DESCRIPTION
**Pull request by vapier**
This brings cmake up to par with the autotools builds and handling of version information.

### CODE REVIEW

**Comment by pierrejoye** [comment]
What do you think about using:

cat src/gd.h | grep ^'#define GD_MAJOR_VERSION' |awk '{print $3}'

so we do not have to install perl anymore?

**Comment by vapier** [comment]
i don't have a prob rewriting `getver.pl` as `getver.sh`

on the autotools side, this isn't an issue because the `configure.ac`->`configure` process itself requires perl (via autotools), and `getver.pl` is only executed at `autoconf` time.  it's new on the cmake side because there is no bootstrap process.

we could update `bootstrap.sh` to do the insertion into the cmake files too, but since cmake doesn't have a bootstrap process otherwise, it doesn't feel quite right.

**Comment by pierrejoye** [comment]
Ah right. I will create another script for windows and maybe for cmake.
Could ve handy.

**Comment by vapier** [comment]
you mean a replacement of getver.pl ?  we could have bootstrap.sh generate/update files that get committed so the windows files stay in sync.

**Comment by vapier** [comment]
did you want me to change something here ?  or shall we move forward with this version and we can land follow up improvements as need be ?

**Comment by pierrejoye** [comment]
We are fine I think.

Thanks :)

**Pull request merged**
