### PR TITLE
Add complex text layout support

### PR DESCRIPTION
**Pull request by khalidalqassabi**
Since Asma is very busy, this PR is based on her work #196 except  travis changes.

### CODE REVIEW

**Comment by vapier** [comment]
please squash the three commits into one instead of doing a merge and reverting stuff

**Comment by khalidalqassabi** [comment]
@vapier done.

**Comment by vapier** [comment]
merged, thanks!

**Comment by pierrejoye** [comment]
Ping? 

We can revisit that afterwards and evaluate how we support it, core or not. :)

**Comment by vapier** [comment]
they left a comment in #196 for you

**Comment by pierrejoye** [comment]
These comments do not answer the question about the library itself. I will
leave alone the last comment, kind of troll ;)

It is not urgent anyway. I will take a deeper look at the lib and its cross
platforms support, let see :)

they left a comment in #196 <https://github.com/libgd/libgd/pull/196> for
you

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/libgd/libgd/pull/246#issuecomment-231527645>, or mute
the thread
<https://github.com/notifications/unsubscribe/AARPKCFvcMP39wohAt7nCTmBLo9pbs1_ks5qT3fVgaJpZM4JA4Ty>
.

**Comment by pierrejoye** [comment]
@vapier can you revert it pls?

It can be merged for 2.3 but right now it is a kind of stopper for other issues in this area. It makes fixes harder for the time being.

It can also be done in a branch and we can port it then.

**Pull request merged**
