### PR TITLE
CMakeLists.txt: Exclude libm dependency under win

### PR DESCRIPTION
**Pull request by willson-chen**
libm is unavaible under win

### CODE REVIEW

**Comment by vapier** [comment]
in autotools, we just link -lm all the time if it's available.  how about we do that here too.

change the two `ADD_GD_TESTS(m)` to `ADD_GD_TESTS()`, and move the win32/m logic into cmake/modules/gd.cmake.

**Comment by willson-chen** [comment]
> in autotools, we just link -lm all the time if it's available. how about we do that here too.
>
>change the two ADD_GD_TESTS(m) to ADD_GD_TESTS(), and move the win32/m logic into cmake/modules/gd.cmake.
Good idear

**Comment by vapier** [comment]
thx bud

**Comment by willson-chen** [comment]
You are the most professinal committer I have ever met. @vapier

**Pull request merged**
