### PR TITLE
Add gdImageGammaCorrect()

### PR DESCRIPTION
**Pull request by cmb69**
Gamma correction can be very useful, so we add a respective function.

### CODE REVIEW

**Comment by cmb69** [comment]
I've forgot to mention that this is basically a port of [imagegammacorrect()](https://github.com/php/php-src/blob/PHP-7.0.11/ext/gd/gd.c#L3029-L3078) of the PHP libgd bindings.

**Comment by pierrejoye** [comment]
+1 :)

**Comment by vapier** [comment]
seems pretty straightforward.  time to merge ? :)

**Comment by cmb69** [comment]
Rebased onto master and force-pushed. Feel free to press the button, Mike! :)

**Pull request closed without merging**
