### PR TITLE
Use pkg-config path hints in "FindFreeType.cmake" #445

### PR DESCRIPTION
**Pull request by az6667**
In some distros (Fedora/Centos), finding "freetype" would fail.
This asks pkg-config for some help. Recycled the pkg-config
example that was in "FindFontConfig.h"

### CODE REVIEW

**Comment by az6667** [comment]
If I'm not doing these pull requests how you'd prefer, please let me know.

**Comment by vapier** [comment]
we're taking FindFreeType.cmake from the cmake project.  can you send your fixes to them ?

**Comment by az6667** [comment]
absolutely. I'll close this pull request.

**Comment by az6667** [comment]
I assumed you meant "please commit to upstream instead"?
It looks like it was fixed in cmake at least as far back as v2.8.12.2

**Comment by vapier** [comment]
i mean we're OK with pulling changes from the cmake project, but we don't want to diverge from them

**Pull request closed without merging**
