### PR TITLE
fix test when libraqm is used

### PR DESCRIPTION
**Pull request by remicollet**
The difference is really minor (1 pixel)

Another way is to always allow 1 pixel difference.

### CODE REVIEW

**Comment by vapier** [comment]
this fixes #655 right ?

i'd be amenable to having the `if (brect[j] != EXPECT[i][j])` check accept a one-pixel diff everywhere.  wdyt ?

```
// Allow a little fuzz diff between the reference and the active font renderer.
if (brect[j] < EXPECT[i][j] - 1 || brect[j] > EXPECT[i][j] + 1) {
```

**Comment by remicollet** [comment]
> i'd be amenable to having the if (brect[j] != EXPECT[i][j]) check accept a one-pixel diff everywhere. wdyt ?

Yes, if was my "Another way" proposal

> this fixes #655 right ?

Yes

**Comment by remicollet** [comment]
Simpler way pushed

**Comment by remicollet** [comment]
Merged

**Pull request closed without merging**
