### PR TITLE
windows/Makefile.vc: Solve the exception that nmake compiles and runs the test report getline does not exist

### PR DESCRIPTION
**Pull request by willson-chen**
Solve the exception that nmake compiles and runs the test report getline does not exist.

### CODE REVIEW

**Comment by vapier** [comment]
BGD_DECLARE & gd.h are for things the library itself exports.  we def don't want to add getline to libgd's API.  if this is only for programs/tests, we should add them to such internal support libs.

it seems like we keep growing more & more logic to replace things that are in POSIX like your #520 PR.  we need to centralize this somewhere as the ad-hoc logic in src/ and tests/ and gdtest.c is getting out of hand.  i'm somewhat inclined to integrate something like gnulib ...

**Comment by willson-chen** [comment]
> BGD_DECLARE & gd.h are for things the library itself exports. we def don't want to add getline to libgd's API. if this is only for programs/tests, we should add them to such internal support libs.

My mistake. I will fix it soon.

> it seems like we keep growing more & more logic to replace things that are in POSIX like your #520 PR. 

Yeah, I tried to improve windows building recently, including cmake, nmake and mingw, which is an important part of milestone 2.2.6.

> we need to centralize this somewhere as the ad-hoc logic in src/ and tests/ and gdtest.c is getting out of hand. i'm somewhat inclined to integrate something like gnulib ...

Sounds good, could you specify how to do?

**Comment by pierrejoye** [comment]
Could you update CMake and configure as well for getline please? Or is it not needed?

**Comment by pierrejoye** [comment]
we will drop makefiles for windows. CMake is the way. It works for visual studio and mingw (see the CI).

**Pull request closed without merging**
