### PR TITLE
CMakeLists.txt: Fixed cmake failed with ENABLE_LIQ=1

### PR DESCRIPTION
**Pull request by willson-chen**
Target ${GD_LIB_STATIC} does not exist while BUILD_STATIC_LIBS is off. And the space in the beginning of the lines is replace by tabs.

### CODE REVIEW

**Comment by willson-chen** [comment]
I found this PR is similar to PR #388. If this PR can be merge, #388 can be closed as well.

**Comment by vapier** [comment]
if we delete the code as discussed in #534, then this block of code would also be deleted

**Comment by willson-chen** [comment]
> if we delete the code as discussed in #534, then this block of code would also be deleted

yeah, let me close this RP.

**Comment by willson-chen** [comment]
This block of code in this PR is unneeded.

**Pull request closed without merging**
