### PR TITLE
Fix #453: drop support for VMS

### LINKED ISSUE #453: drop support for VMS
does anyone care about [VMS](https://en.wikipedia.org/wiki/OpenVMS) anymore ?  realistically, none of us have ever tested on it, and we have no way of doing so, and we haven't had any report on the topic in years.

so lets drop it in GD-2.3

### PR DESCRIPTION
**Pull request by willson-chen**

### CODE REVIEW

**Comment by vapier** [comment]
i've fine with this, but might be good to wait for 2.4

@pierrejoye might have an opinion

**Comment by willson-chen** [comment]
> i've fine with this, but might be good to wait for 2.4
suspend this pr, or create gd-2.4.0-dev branch and merge it?

> @pierrejoye might have an opinion
how to connect with @pierrejoye, please? i am longing to have a conversation with him.

and should i send email to your gmail to discuss the develop plan about libgd?

**Comment by vapier** [comment]
we'll just leave this PR alone until after gd-2.3 branches, then we can merge this into master

hopefully by just tagging @pierrejoye will be enough to get his attention

**Comment by willson-chen** [comment]
> we'll just leave this PR alone until after gd-2.3 branches, then we can merge this into master

do we have a plan to relase 2.2.6 or 2.3? it has been a long time since libgd's last release

**Comment by willson-chen** [comment]
> > we'll just leave this PR alone until after gd-2.3 branches, then we can merge this into master
> 
> do we have a plan to relase 2.2.6 or 2.3? it has been a long time since libgd's last release

especially 2.2.5 contains some vulns. it is not friendly to libgd user.

**Comment by vapier** [comment]
rebased & merged as 8df65487ff0ba98771ed865be80a2d47c91fcc4b

**Pull request closed without merging**
