### PR TITLE
Remove config.h in gdpp.h

### PR DESCRIPTION
**Pull request by willson-chen**
Reference to Issue #345 and PR #491

### CODE REVIEW

**Comment by vapier** [comment]
you'll need to update gdpp.cxx too to not refer to the header or the jpeg defines

**Comment by willson-chen** [comment]
> you'll need to update gdpp.cxx too to not refer to the header or the jpeg defines

sorry. missed that. :)

pls review again.

**Comment by willson-chen** [comment]
umm... the indentations in `gdpp.cxx` is a bit of strange. should i correct them?

```
namespace GD
	{
	bool Image::CreateFrom(FILE * in)
		{
		bool rtn;
		int c = fgetc(in);
```

**Comment by vapier** [comment]
the style in the codebase is often inconsistent :/.  i wouldn't worry about it unless we can come up with some tooling to enforce it & make it easy.

**Pull request merged**
