### PR TITLE
Add missing static qualifiers

### PR DESCRIPTION
**Pull request by crrodriguez**
Suboptimal code is generated because multiple functions lack of static qualifier . This PR fixes most

### CODE REVIEW

**Comment by vapier** [comment]
if it links and passes tests, then should be OK.  at a glance, the funcs seem OK too.  thx bud.

**Comment by vapier** [comment]
this has made our [fuzzer builder unhappy](https://oss-fuzz-build-logs.storage.googleapis.com/log-0c2e8370-fc6a-4602-a992-351fbe264e6d.txt).  could you take a look please ?

```
Step #3 - "compile-afl-address-x86_64": [1mgd_rotate.c:21:13: [0m[0;1;31merror: [0m[1munused function 'gdImageSkewX' [-Werror,-Wunused-function][0m
Step #3 - "compile-afl-address-x86_64": static void gdImageSkewX (gdImagePtr dst, gdImagePtr src, int uRow, int iOffset, double dWeight, int clrBack, int ignoretransparent)
Step #3 - "compile-afl-address-x86_64": [0;1;32m            ^
Step #3 - "compile-afl-address-x86_64": [0m[1mgd_rotate.c:129:13: [0m[0;1;31merror: [0m[1munused function 'gdImageSkewY' [-Werror,-Wunused-function][0m
Step #3 - "compile-afl-address-x86_64": static void gdImageSkewY (gdImagePtr dst, gdImagePtr src, int uCol, int iOffset, double dWeight, int clrBack, int ignoretransparent)
Step #3 - "compile-afl-address-x86_64": [0;1;32m            ^
...
Step #3 - "compile-afl-address-x86_64": [1mgd_interpolation.c:1911:13: [0m[0;1;31merror: [0m[1munused function 'gdDumpRect' [-Werror,-Wunused-function][0m
Step #3 - "compile-afl-address-x86_64": static void gdDumpRect(const char *msg, gdRectPtr r)
Step #3 - "compile-afl-address-x86_64": [0;1;32m            ^
```

**Comment by crrodriguez** [comment]
Yes, those functions are dead now.. unused. we need to remove them.

**Comment by vapier** [comment]
@crrodriguez i've fixed it now ... but as the author of said breakage, it's kind of expected you'd send a follow up PR to fix it

**Pull request merged**
