### PR TITLE
Fix #164: update doc files install directory in CMakeLists.txt

### LINKED ISSUE #164: parity with CMake infrastructure vs autotools
Trying to convert the OpenBSD port / package over from the autoconf build infrastructure to CMake I have found some bits that are not installed which should be and some other nits..

bin/gdlib-config
include/entities.h
include/gdpp.h
lib/pkgconfig/gdlib.pc

And these files are installed but right into share/docs instead of a subdirectory plus the more common name is share/doc... so could they be installed into share/doc/gd?

share/docs/
share/docs/INSTALL
share/docs/README.CMAKE
share/docs/README.JPN
share/docs/README.TESTING
share/docs/README.TXT
share/docs/arc.c
share/docs/copyrotated.c
share/docs/crop.c
share/docs/flip.c
share/docs/gif.c
share/docs/nnquant.c
share/docs/noIcon.pic
share/docs/noIcon.sgi
share/docs/noIcon.tga
share/docs/noIconAlpha.tga
share/docs/test_crop_threshold.png
share/docs/tgaread.c
share/docs/tiffread.c
share/docs/windows.c

### PR DESCRIPTION
**Pull request by willson-chen**
Change install directory from 'share/docs' to 'share/doc/gd'.

### CODE REVIEW

**Comment by willson-chen** [comment]
`share/doc` is wilely used for the software doc files in Linux.

**Comment by vapier** [comment]
`/usr/share/doc/` is fine, but normally packages do `<name>-<version>` rather than just `<name>`.  i think you can get that here with `${PACKAGE_NAME}-${GDLIB_VERSION}`.  i don't know if there's a cmake builtin that'd get you something equiv.

**Comment by willson-chen** [comment]
> `/usr/share/doc/` is fine, but normally packages do `<name>-<version>` rather than just `<name>`. i think you can get that here with `${PACKAGE_NAME}-${GDLIB_VERSION}`. i don't know if there's a cmake builtin that'd get you something equiv.

`GDLIB_VERSION` contains `GDLIB_MAJOR`, `GDLIB_MINOR`, `GDLIB_REVISION` and `GDLIB_EXTRA`. What about `${PACKAGE_NAME}${GDLIB_MAJOR}`? In current version, that equals to `gd2`.
 I think libgd user does not want a new doc dir when a new revision or minor version is released.

**Comment by vapier** [comment]
i'm aware it contains all of those.  it should be fine.

if you wanted to drop GDLIB_REVISION/GDLIB_EXTRA, that's prob fine too.

another option might be to just delete all of these installs and leave it to the distro to handle.  the autotools code isn't installing the doc files and people don't seem to have minded.

**Comment by willson-chen** [comment]
I prefer droping GDLIB_REVISION/GDLIB_EXTRA. :)
Maybe some users need the doc files after intallation. So let's keep these installs.

**Comment by willson-chen** [comment]
I checked the dir `/usr/share/doc`. Most of softwares use `${NAME}${MAJOR}.${MINOR}`, like `python2.7`, `python3.6`. So I delete the dash between ${NAME} and ${MAJOR}.

**Comment by vapier** [comment]
lets stick with `gd-${GDLIB_MAJOR}.${GDLIB_MINOR}`.  python has existing naming that aligns with the dashless form that doesn't really apply to gd.

**Comment by willson-chen** [comment]
> lets stick with `gd-${GDLIB_MAJOR}.${GDLIB_MINOR}`. python has existing naming that aligns with the dashless form that doesn't really apply to gd.

Sounds reasonable. It's done.

thx

**Pull request merged**
