### PR TITLE
Adjusting CMakeLists.txt for #472

### PR DESCRIPTION
**Pull request by kohldampfer**
This commit should solve the problem described in Issue #472

### CODE REVIEW

**Comment by vapier** [comment]
looks like you'll need to rebase onto master.  the diff looks good to me, so i'll squash all of the commits into one, but you still need to rebase to resolve the conflicts.  thanks!

**Comment by willson-chen** [comment]
@vapier hi, we can merge this PR and close the issue #472

**Comment by vapier** [comment]
i mentioned above already -- you need to rebase onto master.  there are conflicts currently that is preventing merging.

**Comment by willson-chen** [comment]
@kohldampfer  can you rebase?

**Comment by willson-chen** [comment]
@kohldampfer Sorry bud, I copied this PR to #582, and made some improvement. I will close this PR if the new one is merged. But if you could come back before that and rebase, I will happily merge this PR instead.

Thanks for your contribution all the same.

**Comment by willson-chen** [comment]
PR #582 merged. I will close this PR. Thank you. @kohldampfer

**Pull request closed without merging**
