### PR TITLE
cmake fixes

### PR DESCRIPTION
**Pull request by rkanavath**
when building libgb with libimagequant it complains about gdstatic target does not exists. first commit fixes that.

second commit uses $(MAKE) which can be gmake or make. This is required when building on bsd oses where 'make' is actually 'bsdmake' and not gnu make.

### CODE REVIEW

**Comment by rkanavath** [comment]
i had tested libimagequant issue and the fix works for me. did you tested this on a local build?

if shared and static both can be built at same time, then the first commit must be updated. In that case, a check for target gd_static should be done before adding dependencies to that target

**Comment by rkanavath** [comment]
here is the cmake output from a fresh build
```

CONFIG='''cmake -DENABLE_FONTCONFIG=ON -DENABLE_FREETYPE=ON -DENABLE_JPEG=ON -DENABLE_LIQ=ON -DENABLE_PNG=ON -DENABLE_TIFF=ON -DENABLE_WEBP=ON -DENABLE_XPM=ON -DBUILD_TEST=ON ../sources '''

-- The C compiler identification is GNU 4.2.1
-- The CXX compiler identification is GNU 4.2.1
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- gd version 2.3.0-dev
-- gd shared lib version 3 (3.0.8)
-- Looking for include file dirent.h
-- Looking for include file dirent.h - found
-- Looking for include file errno.h
-- Looking for include file errno.h - found
-- Looking for include file inttypes.h
-- Looking for include file inttypes.h - found
-- Looking for include file limits.h
-- Looking for include file limits.h - found
-- Looking for include file stddef.h
-- Looking for include file stddef.h - found
-- Looking for include file stdint.h
-- Looking for include file stdint.h - found
-- Looking for include file stdlib.h
-- Looking for include file stdlib.h - found
-- Looking for include file string.h
-- Looking for include file string.h - found
-- Looking for include file strings.h

-- Looking for include file strings.h - found
-- Looking for include file unistd.h
-- Looking for include file unistd.h - found
-- Looking for include file sys/stat.h
-- Looking for include file sys/stat.h - found
-- Looking for include file sys/types.h
-- Looking for include file sys/types.h - found
-- Found ZLIB: /usr/lib/libz.so.5.0 (found version "1.2.3") 
-- Found PNG: /usr/local/lib/libpng.so.17.3 (found version "1.6.23") 
-- Found WEBP: /usr/local/lib/libwebp.so.3.0
-- LIQ will be built
-- Found JPEG: /usr/local/lib/libjpeg.so.68.1  
-- Found TIFF: /usr/local/lib/libtiff.so.39.2 (found version "4.0.6") 
-- Could NOT find Freetype (missing:  FREETYPE_INCLUDE_DIRS) 
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.27.1") 
-- Found Fontconfig: /usr/X11R6/lib/libfontconfig.so.10.0  
-- gd include dir: /home/rashad/projects/libgd/sources/src;/home/rashad/projects/libgd/sources
-- gd libs dir: 
CMake Error at CMakeLists.txt:262 (ADD_DEPENDENCIES):
  Cannot add target-level dependencies to non-existent target "gd_static".

  The add_dependencies works for top-level logical targets created by the
  add_executable, add_library, or add_custom_target commands.  If you want to
  add file-level dependencies see the DEPENDS option of the add_custom_target
  and add_custom_command commands.


-- Configuring incomplete, errors occurred!
See also "/home/rashad/projects/libgd/build/CMakeFiles/CMakeOutput.log".

```

**Comment by vapier** [comment]
"it builds for me" does not address the issues i raised.  commit messages must contain concrete details, and your code still mishandles the case of shared+static libs being enabled.

**Comment by willson-chen** [comment]
@rkanavath Hi, I created a PR #531 similar to this PR to improve CMakeLists.txt.

I have tried your commit on using `${MAKE}` instead `make` in FindLIQ.cmake. But ${MAKE} is null. Could you help me on how to set this var, please? I will create a new PR to update FindLIQ.cmake soon. Once your patch works, I will contain it in my new PR if you don't mind.

**Comment by willson-chen** [comment]
IMHO, this PR is out of date, for we had delete LIQ_BUILD branch in CMakeLists.txt in PR #534. @vapier

**Pull request closed without merging**
