### PR TITLE
Fix #610: Add getlib.sh to tar ball in config/Makefile.am

### LINKED ISSUE #610: 2.3.0: missing config/getlib.sh in dist tar ball
By this gd_LT_CURRENT, gd_LT_REVISION and gd_LT_AGE are empoty and linking fails with:
```
[tkloczko@barrel libgd-2.3.0]$ make
Making all in src
make[1]: Entering directory '/home/tkloczko/rpmbuild/BUILD/libgd-2.3.0/src'
make  all-am
make[2]: Entering directory '/home/tkloczko/rpmbuild/BUILD/libgd-2.3.0/src'
/bin/sh ../libtool  --tag=CC   --mode=link gcc  -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -flto=auto -flto-partition=none -DDEFAULT_FONTPATH='"/usr/share/fonts/bitstream-vera:/usr/share/fonts/dejavu:/usr/share/fonts/default/Type1:/usr/share/X11/fonts/Type1:/usr/share/fonts/liberation"' -fvisibility=hidden -version-info :: -no-undefined -Wl,-z,relro -Wl,--as-needed  -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -flto=auto -flto-partition=none -fuse-linker-plugin -o libgd.la -rpath /usr/lib64 gd.lo gd_bmp.lo gd_color.lo gd_color_map.lo gd_color_match.lo gd_crop.lo gd_filename.lo gd_filter.lo gd_gd.lo gd_gd2.lo gd_gif_in.lo gd_gif_out.lo gd_interpolation.lo gd_io.lo gd_io_dp.lo gd_io_file.lo gd_io_ss.lo gd_jpeg.lo gd_matrix.lo gd_nnquant.lo gd_png.lo gd_rotate.lo gd_security.lo gd_ss.lo gd_tga.lo gd_tiff.lo gd_topal.lo gd_transform.lo gd_version.lo gd_wbmp.lo gd_webp.lo gd_xbm.lo gdcache.lo gdfontg.lo gdfontl.lo gdfontmb.lo gdfonts.lo gdfontt.lo gdft.lo gdfx.lo gdhelpers.lo gdkanji.lo gdtables.lo gdxpm.lo wbmp.lo  -lm   -lz   -lpng16 -lz   -lfreetype   -lfontconfig -lfreetype   -ljpeg    -limagequant -fopenmp  -lXpm -lX11   -ltiff    -lwebp
libtool:   error: CURRENT '' must be a nonnegative integer
libtool:   error: '::' is not valid version information
make[2]: *** [Makefile:777: libgd.la] Error 1
make[2]: Leaving directory '/home/tkloczko/rpmbuild/BUILD/libgd-2.3.0/src'
make[1]: *** [Makefile:634: all] Error 2
make[1]: Leaving directory '/home/tkloczko/rpmbuild/BUILD/libgd-2.3.0/src'
```

### PR DESCRIPTION
**Pull request by willson-chen**

### CODE REVIEW

**Comment by willson-chen** [comment]
@remicollet have fixed this in [635dd9](https://github.com/libgd/libgd/commit/635dd9a3065ed88e1741e6b963044b80e913f96a). I will close this PR.

**Comment by remicollet** [comment]
@willson-chen sorry, I encounter this issue, but haven't notice your PR, so have fix it on my side...

**Comment by willson-chen** [comment]
@remicollet that's fine. :)

Nice to see you back.

BTW, I release GD-2.3.0 myself. But I do not have right to release the release page in `libgd.github.io` for 2.3.0. Do you have right to do merge my PR in that repo? Or could you grant me the privilage?

**Comment by remicollet** [comment]
> Or could you grant me the privilege?

Done

**Comment by willson-chen** [comment]
> > Or could you grant me the privilege?
> 
> Done

Thanks a lot!!! :)

The epidemic is sever in France. Hope you and your family are safe.

**Pull request closed without merging**
