### PR TITLE
Minor patches to address compilation warnings.

### PR DESCRIPTION
**Pull request by davidchappelle**
This patch fixes a few annoying compiler warnings.

### CODE REVIEW

**Comment by vapier** [comment]
please do not mix whitespace & non-whitespace changes

**Comment by davidchappelle** [comment]
Sorry about that. My vim settings are set to auto-remove trailing whitespace.

**Comment by davidchappelle** [comment]
Are you waiting for me to rework a patch?

**Comment by vapier** [comment]
I'm still seeing white space changes mixed in. I'm not going to merge them. if you want to fix the commits and upload them, then can take another look.

**Comment by vapier** [comment]
i guess moved to pull request 153.  you can re-use existing pull requests if you wanted.

**Pull request closed without merging**
