### PR TITLE
WebPDecodeARGB()'s return should be WebPFree()ed.

### PR DESCRIPTION
**Pull request by Maeyanie**
According to Google's spec, "The code that calls any of these functions must delete the data buffer (uint8_t*) returned by these functions with WebPFree()."
Using free() instead was causing heap corruption crashes for me (Windows MSVC 2019 compile)

### CODE REVIEW

**Comment by vapier** [comment]
@morsssss

**Comment by cmb69** [comment]
Thank you! This looks correct, but shouldn't we change the following as well:
https://github.com/libgd/libgd/blob/dbe3001a125003adb553b9e1cd9443353b1df56a/src/gd_webp.c#L232

**Comment by Maeyanie** [comment]
Yes, looks like that should be changed too, good catch. My particular application only used the decoder half, so I didn't run into that one.

**Review by cmb69 — APPROVED** [review]
Thank you! This looks good to me (ref: https://developers.google.com/speed/webp/docs/api#simple_decoding_api). The failing test is unrelated to this PR.

Maybe we should wait a while for others to comment.

**Pull request merged**
