### PR TITLE
Fix "Run tests" step for windows mingw CI

### PR DESCRIPTION
**Pull request by dg0yt**
~Use script syntax for `command.com` instead of `sh`.~
Fix construction of `TMP` path.

### CODE REVIEW

**Comment by vapier** [comment]
> Given that this CI configuration is using msys2 running on windows, and that cmake doesn't need bash, one might think that this CI configuration is meant to fill the gap left by maintainers or contributors rarely running windows...

that isn't a gap. we don't care how people invoke e.g. cmake. we assume those tools work.

> AFAIU all (setup-msys2) run invocations in this file use cmd syntax implicitly.
I don't know if there is a simple switch to use bash instead.

I'm referring to this:
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepsshell

**Comment by dg0yt** [comment]
This PR fixes the step which fails. Maybe it is okay to accept this fix until someone is willing to spend the time on changing the default change for all steps in this workflow?

**Comment by dg0yt** [comment]
Back to `bash` syntax: This is what the msys2 shell runs, [via a wrapper](https://github.com/msys2/setup-msys2/blob/5712755334301153e225db75ded6513e237802b1/main.js#L293).
Now using `$PWD` to construct the absolute path of the temporary directory.

**Comment by dg0yt** [comment]
Ping @vapier.

**Comment by dg0yt** [comment]
Ping @vapier.

**Comment by vapier** [comment]
sorry for the delay bud.  this does seem like a much simpler approach, thx.

is the commit message still accurate ?  the script syntax used here isn't command.com iiuc.

**Comment by dg0yt** [comment]
> is the commit message still accurate ? the script syntax used here isn't command.com iiuc.

You are right. I can remove the second line.

**Comment by vapier** [comment]
thx bud for chasing it down

**Pull request merged**
